/**
 * ------------------------------------------------------------------------====
 * REORGANIZED MENU SYSTEM
 * ------------------------------------------------------------------------====
 *
 * Organizes dashboard menus into three categories:
 * 1. Average User - Daily operations and common tasks
 * 2. Sheet Manager - Data management, performance, integrity, automations
 * 3. Administrator - System admin, seed functions, health monitoring
 *
 * To use this menu instead of the default one:
 * - Rename the existing onOpen() function to onOpen_OLD()
 * - Rename this onOpen_Reorganized() function to onOpen()
 */

function onOpen_Reorganized() {
  const ui = SpreadsheetApp.getUi();

  // ------------ AVERAGE USER MENU ------------
  ui.createMenu("👤 Dashboard")
    .addItem("🔄 Refresh All", "refreshCalculations")
    .addSeparator()
    .addSubMenu(ui.createMenu("📊 Dashboards")
      .addItem("🎯 Unified Operations Monitor", "showUnifiedOperationsMonitor")
      .addItem("📊 Main Dashboard", "goToDashboard")
      .addItem("✨ Interactive Dashboard", "openInteractiveDashboard")
      .addItem("🔄 Refresh Interactive Dashboard", "rebuildInteractiveDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔍 Search & Lookup")
      .addItem("🔍 Search Members", "showMemberSearch")
      .addItem("🔍 Quick Member Search", "quickMemberSearch"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📋 Grievance Tools")
      .addItem("➕ Start New Grievance", "showStartGrievanceDialog")
      .addItem("🔄 Grievance Float Toggle", "toggleGrievanceFloat")
      .addItem("🎛️ Float Control Panel", "showGrievanceFloatPanel")
      .addSeparator()
      .addItem("📨 View Message Trail", "showMessageTrail")
      .addItem("🔄 Refresh Admin Highlights", "refreshAdminMessageHighlights"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📁 Google Drive")
      .addItem("📁 Setup Folder for Grievance", "setupDriveFolderForGrievance")
      .addItem("📎 Upload Files", "showFileUploadDialog")
      .addItem("📂 Show Grievance Files", "showGrievanceFiles"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📧 Communications")
      .addItem("📧 Compose Email", "composeGrievanceEmail")
      .addItem("📝 Email Templates", "showEmailTemplateManager")
      .addSeparator()
      .addItem("📧 Email Opt-Out Management", "showOptOutManagementPanel")
      .addItem("📊 Opt-Out Statistics", "showOptOutStatistics")
      .addSeparator()
      .addItem("📞 View Communications Log", "showGrievanceCommunications"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📊 Reports")
      .addItem("📊 Custom Report Builder", "showCustomReportBuilder")
      .addSeparator()
      .addItem("📄 Export Grievances to CSV", "exportGrievancesToCSV")
      .addItem("📄 Export Members to CSV", "exportMembersToCSV"))
    .addSeparator()
    .addSubMenu(ui.createMenu("♿ Accessibility")
      .addItem("♿ ADHD Control Panel", "showADHDControlPanel")
      .addItem("🎨 Theme Manager", "showThemeManager")
      .addSeparator()
      .addItem("🌙 Quick Toggle Dark Mode", "quickToggleDarkMode")
      .addItem("🎯 Activate Focus Mode", "activateFocusMode")
      .addItem("🎯 Deactivate Focus Mode", "deactivateFocusMode"))
    .addSeparator()
    .addSubMenu(ui.createMenu("❓ Help & Support")
      .addItem("🚀 Quick Start Guide", "showQuickStartGuide")
      .addItem("📚 Interactive Tutorial", "showInteractiveTutorial")
      .addItem("🎥 Video Tutorials", "showVideoTutorials")
      .addSeparator()
      .addItem("❓ Context Help (F1)", "showContextHelp")
      .addItem("🔍 Search Help", "showHelpSearch")
      .addItem("⌨️ Keyboard Shortcuts", "showKeyboardShortcuts")
      .addSeparator()
      .addItem("📋 Release Notes", "showReleaseNotes")
      .addItem("🆕 What's New", "showWhatsNew"))
    .addItem("⚡ Quick Actions", "showQuickActionsMenu")
    .addToUi();

  // ------------ SHEET MANAGER MENU ------------
  ui.createMenu("📊 Sheet Manager")
    .addSubMenu(ui.createMenu("💾 Data Management")
      .addItem("💾 Backup & Recovery Manager", "showBackupManager")
      .addSeparator()
      .addItem("💾 Create Backup Now", "createBackup")
      .addItem("✅ Enable Automated Backups", "setupAutomatedBackups")
      .addItem("🔕 Disable Automated Backups", "disableAutomatedBackups")
      .addSeparator()
      .addItem("📊 View Backup Log", "navigateToBackupLog"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Performance")
      .addItem("🗄️ Cache Status Dashboard", "showCacheStatusDashboard")
      .addSeparator()
      .addItem("🔥 Warm Up All Caches", "warmUpCaches")
      .addItem("🗑️ Clear All Caches", "invalidateAllCaches"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔒 Data Integrity")
      .addItem("📊 Data Quality Dashboard", "showDataQualityDashboard")
      .addItem("🔍 Check Referential Integrity", "checkReferentialIntegrity")
      .addSeparator()
      .addItem("✅ Run Bulk Validation", "runBulkValidation")
      .addItem("⚙️ Validation Settings", "showValidationSettings")
      .addSeparator()
      .addItem("📝 Create Change Log Sheet", "createChangeLogSheet")
      .addItem("🆔 Generate Next Member ID", "showNextMemberID")
      .addItem("🆔 Generate Next Grievance ID", "showNextGrievanceID"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔐 PII Protection")
      .addItem("🔐 PII Protection Dashboard", "showPIIProtectionDashboard")
      .addItem("📤 Export with Masked PII", "exportMembersWithMaskedPII")
      .addItem("📊 PII Audit Report", "showPIIAuditReport")
      .addSeparator()
      .addItem("👤 Data Subject Request", "showDataSubjectRequestForm")
      .addItem("🔄 Anonymize Inactive Members", "anonymizeInactiveMembers"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🤖 Automations")
      .addItem("📬 Notification Settings", "showNotificationSettings")
      .addItem("📊 Report Automation Settings", "showReportAutomationSettings")
      .addSeparator()
      .addItem("✅ Enable Daily Deadline Notifications", "setupDailyDeadlineNotifications")
      .addItem("🔕 Disable Deadline Notifications", "disableDailyDeadlineNotifications")
      .addSeparator()
      .addItem("✅ Enable Monthly Reports", "setupMonthlyReports")
      .addItem("✅ Enable Quarterly Reports", "setupQuarterlyReports")
      .addItem("🔕 Disable All Reports", "disableAutomatedReports"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📁 Google Drive Integration")
      .addItem("📁 Batch Create All Folders", "batchCreateGrievanceFolders")
      .addItem("📁 Setup Drive Folders", "setupDriveFolderForGrievance"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📅 Calendar Integration")
      .addItem("📅 Sync Deadlines to Calendar", "syncDeadlinesToCalendar")
      .addItem("👀 View Upcoming Deadlines", "showUpcomingDeadlinesFromCalendar")
      .addSeparator()
      .addItem("🗑️ Clear All Calendar Events", "clearAllCalendarEvents"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📈 Analysis & Insights")
      .addItem("🔮 Predictive Analytics Dashboard", "showPredictiveAnalyticsDashboard")
      .addItem("📈 Generate Full Analysis", "performPredictiveAnalysis")
      .addItem("🔬 Root Cause Analysis", "showRootCauseAnalysisDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Batch Operations")
      .addItem("⚡ Show Batch Operations Menu", "showBatchOperationsMenu")
      .addSeparator()
      .addItem("👤 Bulk Assign Steward", "batchAssignSteward")
      .addItem("📊 Bulk Update Status", "batchUpdateStatus")
      .addItem("📄 Bulk Export to PDF", "batchExportPDF")
      .addItem("📧 Bulk Email Notifications", "batchEmailNotifications")
      .addItem("📝 Bulk Add Notes", "batchAddNotes"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🤖 Smart Assignment")
      .addItem("🤖 Auto-Assign Steward", "showAutoAssignDialog")
      .addItem("📦 Batch Auto-Assign", "batchAutoAssign")
      .addSeparator()
      .addItem("👥 Steward Workload Dashboard", "showStewardWorkloadDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📚 Knowledge Base")
      .addItem("📚 Search FAQ", "showFAQSearch")
      .addItem("➕ Add New FAQ", "showFAQAdmin")
      .addSeparator()
      .addItem("📝 Create FAQ Database", "createFAQSheet"))
    .addToUi();

  // ------------ SETUP MENU ------------
  ui.createMenu("🔧 Setup")
    .addSubMenu(ui.createMenu("🌱 Seed Demo Data")
      .addSubMenu(ui.createMenu("👥 Seed Members")
        .addItem("Seed Members - Toggle 1 (5,000)", "SEED_MEMBERS_TOGGLE_1")
        .addItem("Seed Members - Toggle 2 (5,000)", "SEED_MEMBERS_TOGGLE_2")
        .addItem("Seed Members - Toggle 3 (5,000)", "SEED_MEMBERS_TOGGLE_3")
        .addItem("Seed Members - Toggle 4 (5,000)", "SEED_MEMBERS_TOGGLE_4")
        .addSeparator()
        .addItem("Seed All 20k Members (Legacy)", "SEED_20K_MEMBERS"))
      .addSubMenu(ui.createMenu("📋 Seed Grievances")
        .addItem("Seed Grievances - Toggle 1 (2,500)", "SEED_GRIEVANCES_TOGGLE_1")
        .addItem("Seed Grievances - Toggle 2 (2,500)", "SEED_GRIEVANCES_TOGGLE_2")
        .addSeparator()
        .addItem("Seed All 5k Grievances (Legacy)", "SEED_5K_GRIEVANCES"))
      .addSeparator()
      .addItem("📝 Add Sample Feedback Entries", "addSampleFeedbackEntries"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🗑️ Data Management")
      .addItem("🚨 Nuke All Data (Production Reset)", "nukeSeedData")
      .addItem("🗑️ Nuke ALL Sheet Data (Comprehensive)", "nukeAllSheetData")
      .addItem("⚠️ Clear Core Data Only", "clearAllData"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📋 Dropdown Configuration")
      .addItem("📋 Setup All Dropdowns", "setupAllDropdowns")
      .addItem("📋 Setup Member Directory Dropdowns", "setupMemberDirectoryDropdowns")
      .addItem("📋 Setup Grievance Log Dropdowns", "setupGrievanceLogDropdowns")
      .addItem("🔄 Refresh Steward Dropdowns", "refreshStewardDropdowns")
      .addSeparator()
      .addItem("📈 Extend Validations (10k rows)", "extendValidationsForLargeDataset"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🎨 Dashboard Setup")
      .addItem("🎨 Setup Dashboard Enhancements", "SETUP_DASHBOARD_ENHANCEMENTS")
      .addItem("📊 Populate Analytics Sheets", "populateAllAnalyticsSheets"))
    .addSeparator()
    .addItem("📝 Open Member Google Form", "openMemberGoogleForm")
    .addToUi();

  // ------------ ADMINISTRATOR MENU ------------
  ui.createMenu("⚙️ Administrator")
    .addSubMenu(ui.createMenu("⚠️ System Health")
      .addItem("⚠️ Error Dashboard", "showErrorDashboard")
      .addItem("🏥 Run Health Check", "performSystemHealthCheck")
      .addSeparator()
      .addItem("📊 View Error Trends", "createErrorTrendReport")
      .addItem("🧪 Test Error Logging", "testErrorLogging"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔬 Root Cause Analysis")
      .addItem("🔬 Root Cause Analysis Dashboard", "showRootCauseAnalysisDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔄 Workflow Management")
      .addItem("🔄 Workflow Visualizer", "showWorkflowVisualizer")
      .addItem("🔄 Change Workflow State", "changeWorkflowState")
      .addItem("📊 View Current State", "showCurrentWorkflowState")
      .addSeparator()
      .addItem("📦 Batch Update State", "batchUpdateWorkflowState"))
    .addSeparator()
    .addSubMenu(ui.createMenu("👁️ Column Toggles & View")
      .addItem("Toggle Level 2 Member Columns", "toggleLevel2Columns")
      .addItem("Show All Member Columns", "showAllMemberColumns")
      .addSeparator()
      .addItem("📨 Toggle Admin Message Columns", "toggleAdminMessageColumns")
      .addItem("Show All Grievance Columns", "showAllGrievanceColumns")
      .addItem("🔧 Setup Admin Message Columns", "setupAdminMessageColumns")
      .addItem("⚡ Install Admin Message Trigger", "installAdminMessageTrigger")
      .addSeparator()
      .addItem("🔄 Refresh Grievance Formulas", "refreshGrievanceFormulas")
      .addItem("🔄 Refresh Dashboard Deadlines", "refreshDashboardDeadlines")
      .addItem("🧹 Cleanup Extra Member Columns", "cleanupMemberDirectoryColumns")
      .addSeparator()
      .addSubMenu(ui.createMenu("📁 Admin Tab Visibility")
        .addItem("👁️ Toggle Admin Tabs", "toggleAdminTabs")
        .addItem("🙈 Hide All Admin Tabs", "hideAdminTabs")
        .addItem("👀 Show All Admin Tabs", "showAdminTabs")
        .addItem("📤 Move Admin Tabs to End", "moveAdminTabsToEnd")
        .addSeparator()
        .addItem("👁️ Hide Diagnostics Tab", "hideDiagnosticsTab"))
      .addItem("Reorder Sheets Logically", "reorderSheetsLogically")
      .addItem("Hide Gridlines (Focus Mode)", "hideAllGridlines")
      .addItem("Show Gridlines", "showAllGridlines")
      .addItem("Setup ADHD Defaults", "setupADHDDefaults")
      .addSeparator()
      .addItem("🔧 Run All Dashboard Fixes", "runAllDashboardFixes")
      .addItem("🔄 Clear Grievance Log Row Formatting", "clearGrievanceLogRowFormatting"))
    .addSeparator()
    .addSubMenu(ui.createMenu("↩️ History & Undo")
      .addItem("↩️ Undo/Redo History", "showUndoRedoPanel")
      .addItem("⌨️ Install Undo Shortcuts", "installUndoRedoShortcuts")
      .addSeparator()
      .addItem("↩️ Undo Last Action (Ctrl+Z)", "undoLastAction")
      .addItem("↪️ Redo Last Action (Ctrl+Y)", "redoLastAction")
      .addSeparator()
      .addItem("🗑️ Clear Undo History", "clearUndoHistory"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📱 Mobile & Viewing")
      .addItem("📱 Mobile Dashboard", "showMobileDashboard")
      .addItem("📋 Mobile Grievance List", "showMobileGrievanceList")
      .addSeparator()
      .addItem("📄 Paginated Data Viewer", "showPaginatedViewer"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🧪 Testing")
      .addItem("🧪 Run All Tests", "runAllTests")
      .addItem("🧪 Run Unit Tests", "runUnitTests")
      .addItem("🧪 Run Validation Tests", "runValidationTests")
      .addItem("🧪 Run Integration Tests", "runIntegrationTests")
      .addSeparator()
      .addItem("🧪 Test Deadline Notifications", "testDeadlineNotifications")
      .addItem("🧪 Test Monthly Report", "generateMonthlyReport")
      .addItem("🧪 Test Quarterly Report", "generateQuarterlyReport")
      .addSeparator()
      .addItem("📊 View Test Results", "showTestResults")
      .addItem("🔧 Diagnose Setup", "DIAGNOSE_SETUP")
      .addItem("⚙️ Shortcuts Configuration", "showKeyboardShortcutsConfig")
      .addItem("F1 Context Help", "showContextHelp"))
    .addSeparator()
    .addSubMenu(ui.createMenu("👥 User Roles (RBAC)")
      .addItem("Initialize RBAC", "initializeRBAC")
      .addItem("Configure Roles", "configureUserRoles")
      .addSeparator()
      .addItem("Add Admin", "addAdmin")
      .addItem("Add Steward", "addSteward")
      .addItem("Add Viewer", "addViewer")
      .addSeparator()
      .addItem("My Permissions", "showMyPermissions"))
    .addSeparator()
    .addItem("👁️ Toggle Setup Menu Visibility", "toggleSetupMenuVisibility")
    .addToUi();
}
