/**
 * ------------------------------------------------------------------------====
 * REORGANIZED MENU SYSTEM
 * ------------------------------------------------------------------------====
 *
 * Comprehensive menu system with 43+ features organized into four categories:
 * 1. 👤 Dashboard - Daily operations, search, grievance tools, communications
 * 2. 📊 Sheet Manager - Data, performance, integrity, automations, analytics
 * 3. 🎭 Demo - Config defaults, data management
 * 4. ⚙️ Administrator - System health, workflow, column toggles, RBAC
 *
 * This file defines createReorganizedMenus(ui) which is called from Code.gs onOpen()
 * The 🧪 Tests menu is defined separately in Code.gs
 */

/**
 * Creates the reorganized menus - called from Code.gs onOpen()
 * This is the main entry point for menu creation
 * @param {Ui} ui - The UI object from SpreadsheetApp
 */
function createReorganizedMenus(ui) {
  if (!ui) {
    ui = SpreadsheetApp.getUi();
  }

  // ------------ AVERAGE USER MENU ------------
  ui.createMenu("👤 Dashboard")
    .addItem("🔄 Refresh All", "refreshCalculations")
    .addSeparator()
    .addSubMenu(ui.createMenu("📊 Dashboards")
      .addItem("🎯 Unified Operations Monitor", "showUnifiedOperationsMonitor")
      .addItem("📊 Main Dashboard", "goToDashboard")
      .addItem("✨ Interactive Dashboard", "openInteractiveDashboard")
      .addItem("🔄 Refresh Interactive Dashboard", "rebuildInteractiveDashboard")
      .addSeparator()
      .addItem("📊 Benchmark Dashboard", "showBenchmarkDashboard")
      .addItem("📈 Visualization Builder", "showVisualizationBuilder")
      .addItem("⚡ Cached Dashboard (Fast)", "showCachedDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔍 Search & Filter")
      .addItem("🔍 Search Members", "showMemberSearch")
      .addItem("🔍 Quick Member Search", "quickMemberSearch")
      .addSeparator()
      .addItem("🔎 Advanced Search", "showSearchDialog")
      .addItem("🎛️ Advanced Filtering", "showFilterDialog")
      .addItem("⚡ Quick Filters", "showQuickFilterMenu")
      .addSeparator()
      .addItem("💾 Saved Searches", "showSavedSearches")
      .addItem("🔖 Bookmarks", "showBookmarks"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📋 Grievance Tools")
      .addItem("➕ Start New Grievance", "showStartGrievanceDialog")
      .addItem("📋 My Assigned Grievances", "showMyAssignedGrievances")
      .addSeparator()
      .addItem("🔄 Grievance Float Toggle", "toggleGrievanceFloat")
      .addItem("🎛️ Float Control Panel", "showGrievanceFloatPanel")
      .addSeparator()
      .addItem("📨 View Message Trail", "showMessageTrail")
      .addItem("🔄 Refresh Admin Highlights", "refreshAdminMessageHighlights"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📁 Google Drive")
      .addItem("📁 Setup Folder for Grievance", "setupDriveFolderForGrievance")
      .addItem("📎 Upload Files", "showFileUploadDialog")
      .addItem("📂 Show Grievance Files", "showGrievanceFiles"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📧 Communications")
      .addItem("📧 Compose Email", "composeGrievanceEmail")
      .addItem("📝 Email Templates", "showEmailTemplateManager")
      .addSeparator()
      .addItem("🔔 Notification Center", "showNotificationCenter")
      .addSeparator()
      .addItem("📧 Email Opt-Out Management", "showOptOutManagementPanel")
      .addItem("📊 Opt-Out Statistics", "showOptOutStatistics")
      .addSeparator()
      .addItem("📞 View Communications Log", "showGrievanceCommunications"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📊 Reports & Export")
      .addItem("📊 Custom Report Builder", "showCustomReportBuilder")
      .addSeparator()
      .addItem("📤 Export Wizard", "showExportWizard")
      .addItem("📥 Import Wizard", "showImportWizard")
      .addSeparator()
      .addItem("📄 Export Grievances to CSV", "exportGrievancesToCSV")
      .addItem("📄 Export Members to CSV", "exportMembersToCSV")
      .addItem("📊 Advanced Export Options", "showAdvancedExport"))
    .addSeparator()
    .addSubMenu(ui.createMenu("♿ Accessibility")
      .addItem("♿ ADHD Control Panel", "showADHDControlPanel")
      .addItem("🎨 Theme Manager", "showThemeManager")
      .addSeparator()
      .addItem("🌙 Quick Toggle Dark Mode", "quickToggleDarkMode")
      .addItem("🎯 Activate Focus Mode", "activateFocusMode")
      .addItem("🎯 Deactivate Focus Mode", "deactivateFocusMode")
      .addSeparator()
      .addItem("🦓 Toggle Zebra Stripes", "toggleZebraStripes")
      .addItem("🔲 Toggle Gridlines (ADHD)", "toggleGridlinesADHD")
      .addItem("🐢 Toggle Reduced Motion", "toggleReducedMotion"))
    .addSeparator()
    .addSubMenu(ui.createMenu("❓ Help & Support")
      .addItem("👋 Welcome Wizard", "showWelcomeWizard")
      .addItem("🚀 Getting Started Guide", "showGettingStartedGuide")
      .addItem("📚 Interactive Tutorial", "showInteractiveTutorial")
      .addItem("🎥 Video Tutorials", "showVideoTutorials")
      .addSeparator()
      .addItem("❓ Context Help (F1)", "showContextHelp")
      .addItem("📖 Enhanced Help", "showEnhancedHelp")
      .addItem("📋 Column Help", "showColumnHelp")
      .addItem("💡 Quick Tips", "showQuickTips")
      .addSeparator()
      .addItem("🔍 Search Help", "showHelpSearch")
      .addItem("⌨️ Keyboard Shortcuts", "showKeyboardShortcuts")
      .addSeparator()
      .addItem("📋 Release Notes", "showReleaseNotes")
      .addItem("🆕 What's New", "showWhatsNew")
      .addItem("📜 Version History", "showVersionHistory"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Quick Actions")
      .addItem("⚡ Quick Actions Menu", "showQuickActionsMenu")
      .addItem("📌 Quick Actions Sidebar", "showQuickActionsSidebar")
      .addSeparator()
      .addItem("👤 Member Quick Actions", "showMemberQuickActions")
      .addItem("📋 Grievance Quick Actions", "showGrievanceQuickActions")
      .addSeparator()
      .addItem("📝 Quick Capture Notepad", "showQuickCaptureNotepad"))
    .addToUi();

  // ------------ SHEET MANAGER MENU ------------
  ui.createMenu("📊 Sheet Manager")
    .addSubMenu(ui.createMenu("🔄 Config Sync")
      .addItem("🔄 Sync Data → Config (One-Time)", "syncAllDataToConfig")
      .addItem("⚡ Install Auto-Sync Trigger", "installConfigSyncTrigger")
      .addSeparator()
      .addItem("ℹ️ How Config Sync Works", "showConfigSyncHelp"))
    .addSeparator()
    .addSubMenu(ui.createMenu("💾 Data Management")
      .addItem("💾 Backup & Recovery Manager", "showBackupManager")
      .addSeparator()
      .addItem("💾 Create Backup Now", "createBackup")
      .addItem("✅ Enable Automated Backups", "setupAutomatedBackups")
      .addItem("🔕 Disable Automated Backups", "disableAutomatedBackups")
      .addSeparator()
      .addItem("📊 View Backup Log", "navigateToBackupLog"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Performance")
      .addItem("🗄️ Cache Status Dashboard", "showCacheStatusDashboard")
      .addItem("📊 Performance Summary", "showPerformanceSummary")
      .addItem("📱 Device Analytics", "showDeviceAnalyticsDashboard")
      .addItem("👥 Session Dashboard", "showSessionDashboard")
      .addSeparator()
      .addItem("🔥 Warm Up All Caches", "warmUpCaches")
      .addItem("🗑️ Clear All Caches", "invalidateAllCaches"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔒 Data Integrity")
      .addItem("📊 Data Quality Dashboard", "showDataQualityDashboard")
      .addItem("🔍 Check Referential Integrity", "checkReferentialIntegrity")
      .addItem("📋 Validation Report", "showValidationReport")
      .addSeparator()
      .addItem("✅ Run Bulk Validation", "runBulkValidation")
      .addItem("⚙️ Validation Settings", "showValidationSettings")
      .addSeparator()
      .addItem("📝 Create Change Log Sheet", "createChangeLogSheet")
      .addItem("🆔 Generate Next Member ID", "showNextMemberID")
      .addItem("🆔 Generate Next Grievance ID", "showNextGrievanceID"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔐 PII Protection")
      .addItem("🔐 PII Protection Dashboard", "showPIIProtectionDashboard")
      .addItem("📤 Export with Masked PII", "exportMembersWithMaskedPII")
      .addItem("📊 PII Audit Report", "showPIIAuditReport")
      .addSeparator()
      .addItem("👤 Data Subject Request", "showDataSubjectRequestForm")
      .addItem("🔄 Anonymize Inactive Members", "anonymizeInactiveMembers"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🤖 Automations")
      .addItem("📬 Notification Settings", "showNotificationSettings")
      .addItem("📊 Report Automation Settings", "showReportAutomationSettings")
      .addItem("🔄 Auto-Refresh Settings", "showAutoRefreshSettings")
      .addSeparator()
      .addItem("✅ Enable Daily Deadline Notifications", "setupDailyDeadlineNotifications")
      .addItem("🔕 Disable Deadline Notifications", "disableDailyDeadlineNotifications")
      .addSeparator()
      .addItem("✅ Enable Monthly Reports", "setupMonthlyReports")
      .addItem("✅ Enable Quarterly Reports", "setupQuarterlyReports")
      .addItem("🔕 Disable All Reports", "disableAutomatedReports")
      .addSeparator()
      .addItem("⌨️ Setup Keyboard Shortcuts", "setupKeyboardShortcuts")
      .addItem("🔄 Setup Auto-Refresh Trigger", "setupAutoRefreshTrigger")
      .addItem("🔒 Setup Security Monitoring", "setupSuspiciousActivityMonitoring"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📁 Google Drive Integration")
      .addItem("📁 Batch Create All Folders", "batchCreateGrievanceFolders")
      .addItem("📁 Setup Drive Folders", "setupDriveFolderForGrievance"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📅 Calendar Integration")
      .addItem("📅 Sync Deadlines to Calendar", "syncDeadlinesToCalendar")
      .addItem("👀 View Upcoming Deadlines", "showUpcomingDeadlinesFromCalendar")
      .addSeparator()
      .addItem("🗑️ Clear All Calendar Events", "clearAllCalendarEvents"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📈 Analysis & Insights")
      .addItem("🔮 Predictive Analytics Dashboard", "showPredictiveAnalyticsDashboard")
      .addItem("📈 Generate Full Analysis", "performPredictiveAnalysis")
      .addItem("🔬 Root Cause Analysis", "showRootCauseAnalysisDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Batch Operations")
      .addItem("⚡ Show Batch Operations Menu", "showBatchOperationsMenu")
      .addSeparator()
      .addItem("👤 Bulk Assign Steward", "batchAssignSteward")
      .addItem("📊 Bulk Update Status", "batchUpdateStatus")
      .addItem("📄 Bulk Export to PDF", "batchExportPDF")
      .addItem("📧 Bulk Email Notifications", "batchEmailNotifications")
      .addItem("📝 Bulk Add Notes", "batchAddNotes"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🤖 Smart Assignment")
      .addItem("🤖 Auto-Assign Steward", "showAutoAssignDialog")
      .addItem("📦 Batch Auto-Assign", "batchAutoAssign")
      .addSeparator()
      .addItem("👥 Steward Workload Dashboard", "showStewardWorkloadDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📚 Knowledge Base")
      .addItem("📚 Search FAQ", "showFAQSearch")
      .addItem("➕ Add New FAQ", "showFAQAdmin")
      .addSeparator()
      .addItem("📝 Create FAQ Database", "createFAQSheet"))
    .addToUi();

  // ------------ DEMO MENU ------------
  ui.createMenu("🎭 Demo")
    .addItem("🚀 Seed All Sample Data", "SEED_SAMPLE_DATA")
    .addSeparator()
    .addSubMenu(ui.createMenu("🌱 Seed Data")
      .addItem("🚀 SEED FULL DEMO (2K + 300)", "SEED_FULL_DEMO")
      .addSeparator()
      .addItem("👥 Seed 2,000 Members", "SEED_2K_MEMBERS")
      .addItem("📋 Seed 300 Grievances", "SEED_300_GRIEVANCES")
      .addSeparator()
      .addItem("👥 Seed Members (Custom Count)", "SEED_MEMBERS_DIALOG")
      .addItem("📋 Seed Grievances (Custom Count)", "SEED_GRIEVANCES_DIALOG")
      .addSeparator()
      .addItem("⚙️ Seed Config Dropdowns Only", "seedConfigData")
      .addItem("⚙️ Populate Config Defaults (Full)", "populateConfigDefaults")
      .addSeparator()
      .addItem("📊 Populate Member Satisfaction", "populateMemberSatisfaction")
      .addItem("❓ Seed Initial FAQs", "seedInitialFAQs")
      .addSeparator()
      .addItem("🔒 Seed with Rollback Protection", "seedAllWithRollback")
      .addItem("🔐 Seed Thread-Safe", "seedDataThreadSafe"))
    .addSeparator()
    .addItem("📝 Add Sample Feedback Entries", "addSampleFeedbackEntries")
    .addItem("📋 Populate Pending TODOs", "populatePendingTodos")
    .addSeparator()
    .addSubMenu(ui.createMenu("🗑️ Nuke Data")
      .addItem("☢️ NUKE ALL DATA", "NUKE_ALL_DATA")
      .addItem("🧹 Clear Config Dropdowns Only", "NUKE_CONFIG_DROPDOWNS")
      .addSeparator()
      .addItem("🗑️ Clear ALL Sheet Data (Legacy)", "nukeAllSheetData")
      .addItem("⚠️ Clear Core Data Only", "clearAllData")
      .addItem("🔄 Clear with Rollback Protection", "clearAllDataWithRollback"))
    .addToUi();

  // ------------ ADMINISTRATOR MENU ------------
  ui.createMenu("⚙️ Administrator")
    .addSubMenu(ui.createMenu("⚠️ System Health")
      .addItem("⚠️ Error Dashboard", "showErrorDashboard")
      .addItem("🏥 Run Health Check", "performSystemHealthCheck")
      .addItem("📋 Schema Health Check", "showSchemaHealthCheck")
      .addSeparator()
      .addItem("📊 View Error Trends", "createErrorTrendReport")
      .addItem("🧪 Test Error Logging", "testErrorLogging"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔬 Root Cause Analysis")
      .addItem("🔬 Root Cause Analysis Dashboard", "showRootCauseAnalysisDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔄 Workflow Management")
      .addItem("🔄 Workflow Visualizer", "showWorkflowVisualizer")
      .addItem("🔄 Change Workflow State", "changeWorkflowState")
      .addItem("📊 View Current State", "showCurrentWorkflowState")
      .addSeparator()
      .addItem("📦 Batch Update State", "batchUpdateWorkflowState"))
    .addSeparator()
    .addSubMenu(ui.createMenu("👁️ Column Toggles & View")
      .addItem("Toggle Level 2 Member Columns", "toggleLevel2Columns")
      .addItem("Toggle Engagement Metrics", "toggleEngagementMetricsColumns")
      .addItem("Toggle Member Interests", "toggleMemberInterestsColumns")
      .addItem("Toggle Engagement & Interests", "toggleEngagementAndInterestsColumns")
      .addItem("Show All Member Columns", "showAllMemberColumns")
      .addSeparator()
      .addItem("📨 Toggle Admin Message Columns", "toggleAdminMessageColumns")
      .addItem("Show All Grievance Columns", "showAllGrievanceColumns")
      .addItem("🔧 Setup Admin Message Columns", "setupAdminMessageColumns")
      .addItem("⚡ Install Admin Message Trigger", "installAdminMessageTrigger")
      .addSeparator()
      .addItem("🔄 Refresh Grievance Formulas", "refreshGrievanceFormulas")
      .addItem("🔄 Refresh Member Directory Formulas", "refreshMemberDirectoryFormulas")
      .addItem("🔄 Refresh All Formulas", "refreshAllFormulas")
      .addItem("🔄 Refresh Dashboard Deadlines", "refreshDashboardDeadlines")
      .addItem("🧹 Cleanup Extra Member Columns", "cleanupMemberDirectoryColumns")
      .addSeparator()
      .addItem("👁️ Hide Diagnostics Tab", "hideDiagnosticsTab")
      .addItem("Reorder Sheets Logically", "reorderSheetsLogically")
      .addItem("Hide Gridlines (Focus Mode)", "hideAllGridlines")
      .addItem("Show Gridlines", "showAllGridlines")
      .addItem("🎯 Toggle Complexity Indicators", "toggleComplexityIndicators")
      .addItem("Setup ADHD Defaults", "setupADHDDefaults"))
    .addSeparator()
    .addSubMenu(ui.createMenu("↩️ History & Undo")
      .addItem("↩️ Undo/Redo History", "showUndoRedoPanel")
      .addItem("⌨️ Install Undo Shortcuts", "installUndoRedoShortcuts")
      .addSeparator()
      .addItem("↩️ Undo Last Action (Ctrl+Z)", "undoLastAction")
      .addItem("↪️ Redo Last Action (Ctrl+Y)", "redoLastAction")
      .addSeparator()
      .addItem("🗑️ Clear Undo History", "clearUndoHistory"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📱 Mobile & Viewing")
      .addItem("📱 Mobile Dashboard", "showMobileDashboard")
      .addItem("📋 Mobile Grievance List", "showMobileGrievanceList")
      .addItem("📋 Mobile Grievance Browser", "showMobileGrievanceBrowser")
      .addItem("👥 Mobile Member Browser", "showMobileMemberBrowser")
      .addItem("🔍 Mobile Unified Search", "showMobileUnifiedSearch")
      .addSeparator()
      .addItem("📄 Paginated Data Viewer", "showPaginatedViewer"))
    .addSeparator()
    .addSubMenu(ui.createMenu("👥 User Roles (RBAC)")
      .addItem("Initialize RBAC", "initializeRBAC")
      .addItem("Configure Roles", "configureUserRoles")
      .addSeparator()
      .addItem("Add Admin", "addAdmin")
      .addItem("Add Steward", "addSteward")
      .addItem("Add Viewer", "addViewer")
      .addSeparator()
      .addItem("My Permissions", "showMyPermissions"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔧 Setup & Triggers")
      .addItem("🔧 REPAIR DASHBOARD (Fix All Issues)", "REPAIR_DASHBOARD")
      .addItem("⚡ Quick Repair (Formulas Only)", "QUICK_REPAIR")
      .addItem("🔍 Verify Hidden Sheets", "VERIFY_HIDDEN_SHEETS")
      .addSeparator()
      .addItem("📅 Setup Engagement Tracking", "setupEngagementTracking")
      .addItem("📅 Create Meeting Attendance Sheet", "createMeetingAttendanceSheet")
      .addItem("🤝 Create Volunteer Hours Sheet", "createVolunteerHoursSheet")
      .addSeparator()
      .addItem("👨‍⚖️ Setup Steward Workload Auto-Sync", "setupStewardWorkloadAutoSync")
      .addItem("🎯 Setup Interactive Dashboard Live-Wire", "setupInteractiveDashboardLiveSync")
      .addSeparator()
      .addItem("📋 Install Menu Trigger", "installOnOpenTrigger")
      .addItem("🗑️ Remove Menu Trigger", "uninstallOnOpenTrigger")
      .addSeparator()
      .addItem("📋 Initialize Required Sheets", "showSetupRequiredSheets"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚙️ User Settings")
      .addItem("⚙️ Preferences Editor", "showPreferencesEditor")
      .addItem("🌐 Language Selector", "showLanguageSelector"))
    .addToUi();

  // ------------ UTILITIES MENU (Orphan Functions) ------------
  ui.createMenu("🔧 Utilities")
    .addSubMenu(ui.createMenu("🏗️ Dashboard Creation")
      .addItem("🚀 CREATE Full Dashboard", "CREATE_509_DASHBOARD")
      .addItem("⚡ CREATE Lite Dashboard", "CREATE_509_DASHBOARD_LITE")
      .addItem("📦 CREATE Part 2 (Analytics)", "CREATE_509_DASHBOARD_PART2")
      .addSeparator()
      .addItem("🔧 REPAIR Dashboard", "REPAIR_DASHBOARD")
      .addItem("⚡ REBUILD Optimized", "REBUILD_DASHBOARD_OPTIMIZED")
      .addItem("🛡️ REBUILD Safe Mode", "REBUILD_DASHBOARD_SAFE")
      .addItem("🔒 REBUILD Thread-Safe", "rebuildDashboardThreadSafe")
      .addItem("📉 REBUILD Minimal", "rebuildDashboardMinimal")
      .addSeparator()
      .addItem("✨ Setup Dashboard Enhancements", "SETUP_DASHBOARD_ENHANCEMENTS")
      .addItem("🔧 Run All Dashboard Fixes", "runAllDashboardFixes"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Performance & Cache")
      .addItem("📊 View Performance Dashboard", "VIEW_PERFORMANCE_DASHBOARD")
      .addItem("📈 View Performance Log", "viewPerformanceLog")
      .addItem("📊 Show Chart Build Status", "SHOW_CHART_BUILD_STATUS")
      .addItem("🔄 Show Idempotent Status", "SHOW_IDEMPOTENT_STATUS")
      .addItem("🔒 Check Lock Status", "CHECK_LOCK_STATUS")
      .addSeparator()
      .addItem("🗑️ Clear Chart Cache", "CLEAR_CHART_CACHE")
      .addItem("🗑️ Clear Idempotent Cache", "CLEAR_IDEMPOTENT_CACHE")
      .addItem("🔄 Force Rebuild All Charts", "FORCE_REBUILD_ALL_CHARTS"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📤 Export Functions")
      .addItem("📄 Export Grievance to PDF", "exportGrievanceToPDF")
      .addItem("📊 Export Data to CSV", "exportToCSV")
      .addItem("📊 Export Data to JSON", "exportToJSON")
      .addItem("📊 Export to New Sheet", "exportToNewSheet")
      .addSeparator()
      .addItem("📋 Export Activity Log", "exportActivityLog")
      .addItem("📊 Export Benchmark Report", "exportBenchmarkReport")
      .addItem("📋 Export Error Log to Sheet", "exportErrorLogToSheet")
      .addItem("📋 Export Changelog to Sheet", "exportChangelogToSheet")
      .addItem("📋 Export Undo History", "exportUndoHistoryToSheet")
      .addItem("📊 Export Performance Data CSV", "exportPerformanceDataCSV")
      .addSeparator()
      .addItem("📊 Export Interactive Dashboard Summary", "exportInteractiveDashboardSummary")
      .addItem("👥 Export Members with Opt-Out", "exportMembersWithOptOut"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📥 Import Functions")
      .addItem("📥 Import Data", "importData")
      .addItem("📥 Show Import Dialog", "showImportDialog"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📦 Archive & Restore")
      .addItem("📦 Archive Old Grievances", "archiveOldGrievances")
      .addItem("📦 Archive Records", "archiveRecords")
      .addItem("📦 Show Archive Dialog", "showArchiveDialog")
      .addSeparator()
      .addItem("🔄 Restore from Archive", "restoreFromArchive")
      .addItem("🔄 Restore from Backup", "restoreFromBackup")
      .addItem("🔄 Restore from Snapshot", "restoreFromSnapshot"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔄 Batch Recalculations")
      .addItem("🔄 Recalc ALL Grievances (Batched)", "RECALC_ALL_GRIEVANCES_BATCHED")
      .addItem("🔄 Batch Update with Lock", "batchUpdateWithLock")
      .addSeparator()
      .addItem("📊 Sort Grievances by Status", "SORT_GRIEVANCES_BY_STATUS"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📧 Opt-Out Management")
      .addItem("✅ Bulk Opt-In", "bulkOptIn")
      .addItem("❌ Bulk Opt-Out", "bulkOptOut")
      .addItem("📋 Show PII Access Log", "showPIIAccessLog"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔧 Install Triggers")
      .addItem("⚡ Install Essential Triggers", "installEssentialTriggers")
      .addItem("📋 Install Grievance Sync Trigger", "installGrievanceSyncTrigger")
      .addItem("👥 Install Member Sync Trigger", "installMemberSyncTrigger")
      .addItem("📊 Install Engagement Sync Trigger", "installEngagementSyncTrigger")
      .addItem("🤝 Install Steward Contact Sync Trigger", "installStewardContactSyncTrigger")
      .addItem("👨‍⚖️ Install Steward Workload Sync Trigger", "installStewardWorkloadSyncTrigger")
      .addItem("🎯 Install Interactive Dashboard Sync Trigger", "installInteractiveDashboardSyncTrigger")
      .addItem("✅ Install Validation Trigger", "installValidationTrigger")
      .addItem("📊 Install Grievance Auto-Sort Trigger", "installGrievanceAutoSortTrigger"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔧 Setup Functions")
      .addItem("📋 Setup Required Sheets", "setupRequiredSheets")
      .addItem("✅ Setup Data Validations", "setupDataValidations")
      .addItem("📊 Setup Formulas & Calculations", "setupFormulasAndCalculations")
      .addItem("🎛️ Setup All Dropdowns", "setupAllDropdowns")
      .addSeparator()
      .addItem("📋 Setup Grievance Log Dropdowns", "setupGrievanceLogDropdowns")
      .addItem("👥 Setup Member Directory Dropdowns", "setupMemberDirectoryDropdowns")
      .addItem("👥 Setup Member Directory Validations", "setupMemberDirectoryValidations")
      .addSeparator()
      .addItem("🎯 Setup Interactive Dashboard Controls", "setupInteractiveDashboardControls")
      .addItem("📊 Setup Grievance Progress Bar", "setupGrievanceProgressBar")
      .addItem("📊 Setup Days to Deadline Formatting", "setupDaysToDeadlineConditionalFormatting")
      .addItem("🎨 Setup Resolution Column Colors", "setupResolutionColumnColors")
      .addSeparator()
      .addItem("📧 Setup Email Opt-Out Column", "setupEmailOptOutColumn")
      .addItem("🤝 Add Steward Contact Info to Config", "addStewardContactInfoToConfig"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📊 Hidden Calc Sheets")
      .addItem("Setup Grievance Calc Sheet", "setupGrievanceCalcSheet")
      .addItem("Setup Member Lookup Sheet", "setupMemberLookupSheet")
      .addItem("Setup Engagement Calc Sheet", "setupEngagementCalcSheet")
      .addItem("Setup Steward Contact Calc Sheet", "setupStewardContactCalcSheet")
      .addItem("Setup Steward Workload Calc Sheet", "setupStewardWorkloadCalcSheet")
      .addItem("Setup Interactive Dashboard Calc Sheet", "setupInteractiveDashboardCalcSheet")
      .addSeparator()
      .addItem("Sync Grievance Calc → Member Dir", "syncGrievanceCalcToMemberDirectory")
      .addItem("Sync Member Lookup → Grievance Log", "syncMemberLookupToGrievanceLog")
      .addItem("Sync Engagement → Member Dir", "syncEngagementToMemberDirectory")
      .addItem("Sync Steward Contact → Member Dir", "syncStewardContactToMemberDirectory")
      .addItem("Sync Steward Workload Calc → Sheet", "syncStewardWorkloadCalcToSheet")
      .addItem("Sync Interactive Dashboard from Calc", "syncInteractiveDashboardFromCalc"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📋 Reports & Generation")
      .addItem("📊 Generate Monthly Report", "generateMonthlyReport")
      .addItem("📊 Generate Quarterly Report", "generateQuarterlyReport")
      .addItem("📊 Generate Performance Report", "generatePerformanceReport")
      .addItem("📊 Generate Audit Report", "generateAuditReport")
      .addItem("📊 Generate Test Report", "generateTestReport")
      .addSeparator()
      .addItem("🆔 Generate Next Member ID", "generateNextMemberID")
      .addItem("🆔 Generate Next Grievance ID", "generateNextGrievanceID"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔍 Diagnostics & Checks")
      .addItem("🔍 Check Deadlines and Notify", "checkDeadlinesAndNotify")
      .addItem("🔍 Check Duplicate Member ID", "checkDuplicateMemberID")
      .addItem("🔍 Check Duplicate Grievance ID", "checkDuplicateGrievanceID")
      .addItem("🔍 Check Concurrent Operations", "checkConcurrentOperations")
      .addItem("🔍 Check First Time User", "checkFirstTimeUser")
      .addItem("🔍 Check for Updates", "checkForUpdates")
      .addSeparator()
      .addItem("🔐 Run Security Audit", "runSecurityAudit")
      .addItem("📋 Run Schema Health Check", "runSchemaHealthCheck")
      .addItem("🏥 Run Phase 6 Health Check", "runPhase6HealthCheck")
      .addSeparator()
      .addItem("📋 View Audit Log", "viewAuditLog")
      .addItem("🔄 Refresh All Validations", "refreshAllValidations"))
    .addSeparator()
    .addSubMenu(ui.createMenu("👁️ Show/View Functions")
      .addItem("📋 Show All Interactive Dashboard Data", "showAllInteractiveDashboardData")
      .addItem("📋 Show All Records", "showAllRecords")
      .addItem("📊 Show Backup Info", "showBackupInfo")
      .addItem("📋 Show Cached Dashboard", "showCachedDashboard")
      .addItem("❓ Show General Help", "showGeneralHelp")
      .addItem("📋 Show Grievance Communications", "showGrievanceCommunications")
      .addItem("📋 Show Grievance Detail", "showGrievanceDetail")
      .addItem("📁 Show Grievance Files", "showGrievanceFiles")
      .addItem("👥 Show Member Details Dialog", "showMemberDetailsDialog")
      .addItem("📋 Show Member Grievance History", "showMemberGrievanceHistory")
      .addItem("📊 Show Member Satisfaction Tab", "showMemberSatisfactionTab")
      .addItem("🔐 Show My Permissions", "showMyPermissions")
      .addItem("📋 Show Phase 6 Status", "showPhase6Status")
      .addItem("📋 Show Recent Grievances Dialog", "showRecentGrievancesDialog")
      .addItem("🔧 Show Refresh Status", "showRefreshStatus")
      .addItem("👨‍⚖️ Show Steward Workload Dashboard", "showStewardWorkloadDashboard")
      .addItem("📋 Show Task Help", "showTaskHelp")
      .addItem("📜 Show Version History", "showVersionHistory"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📋 Miscellaneous")
      .addItem("📋 Add Grievance to Log", "addGrievanceToLog")
      .addItem("🔗 Add Google Drive Link to Grievance Log", "addGoogleDriveLinkToGrievanceLog")
      .addItem("📋 Add Help Icons to Headers", "addHelpIconsToHeaders")
      .addItem("📋 Assign Steward to Grievance", "assignStewardToGrievance")
      .addItem("🤖 Auto-Assign Steward", "autoAssignSteward")
      .addSeparator()
      .addItem("📁 Open Grievance Drive Folder", "openGrievanceDriveFolder")
      .addItem("📝 Open Grievance Form", "openGrievanceForm")
      .addItem("📝 Open Contact Form", "openContactForm")
      .addItem("👥 Open Member Google Form", "openMemberGoogleForm")
      .addSeparator()
      .addItem("🎨 Apply Dashboard Theme", "applyDashboardTheme")
      .addItem("🌙 Check and Apply Auto Theme", "checkAndApplyAutoTheme")
      .addItem("📊 Apply Grievance Status Bar", "applyGrievanceStatusBar")
      .addItem("🦓 Apply Zebra Stripes", "applyZebraStripes")
      .addSeparator()
      .addItem("☕ Show Break Reminder", "showBreakReminder")
      .addItem("📝 Show Quick Capture Notepad", "showQuickCaptureNotepad"))
    .addToUi();
}

/**
 * Legacy wrapper for backwards compatibility
 * Calls createReorganizedMenus() directly
 */
function onOpen_Reorganized() {
  createReorganizedMenus();
}
