/**
 * ------------------------------------------------------------------------====
 * REORGANIZED MENU SYSTEM
 * ------------------------------------------------------------------------====
 *
 * Comprehensive menu system with 43+ features organized into four categories:
 * 1. 👤 Dashboard - Daily operations, search, grievance tools, communications
 * 2. 📊 Sheet Manager - Data, performance, integrity, automations, analytics
 * 3. 🎭 Demo - Seed demo data, data management (nuke/clear)
 * 4. ⚙️ Administrator - System health, workflow, column toggles, RBAC
 *
 * This file defines createReorganizedMenus(ui) which is called from Code.gs onOpen()
 * The 🧪 Tests menu is defined separately in Code.gs
 */

/**
 * Creates the reorganized menus - called from Code.gs onOpen()
 * This is the main entry point for menu creation
 * @param {Ui} ui - The UI object from SpreadsheetApp
 */
function createReorganizedMenus(ui) {
  if (!ui) {
    ui = SpreadsheetApp.getUi();
  }

  // ------------ AVERAGE USER MENU ------------
  ui.createMenu("👤 Dashboard")
    .addItem("🔄 Refresh All", "refreshCalculations")
    .addSeparator()
    .addSubMenu(ui.createMenu("📊 Dashboards")
      .addItem("🎯 Unified Operations Monitor", "showUnifiedOperationsMonitor")
      .addItem("📊 Main Dashboard", "goToDashboard")
      .addItem("✨ Interactive Dashboard", "openInteractiveDashboard")
      .addItem("🔄 Refresh Interactive Dashboard", "rebuildInteractiveDashboard")
      .addSeparator()
      .addItem("📊 Benchmark Dashboard", "showBenchmarkDashboard")
      .addItem("📈 Visualization Builder", "showVisualizationBuilder")
      .addItem("⚡ Cached Dashboard (Fast)", "showCachedDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔍 Search & Filter")
      .addItem("🔍 Search Members", "showMemberSearch")
      .addItem("🔍 Quick Member Search", "quickMemberSearch")
      .addSeparator()
      .addItem("🔎 Advanced Search", "showSearchDialog")
      .addItem("🎛️ Advanced Filtering", "showFilterDialog")
      .addItem("⚡ Quick Filters", "showQuickFilterMenu")
      .addSeparator()
      .addItem("💾 Saved Searches", "showSavedSearches")
      .addItem("🔖 Bookmarks", "showBookmarks"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📋 Grievance Tools")
      .addItem("➕ Start New Grievance", "showStartGrievanceDialog")
      .addItem("📋 My Assigned Grievances", "showMyAssignedGrievances")
      .addSeparator()
      .addItem("🔄 Grievance Float Toggle", "toggleGrievanceFloat")
      .addItem("🎛️ Float Control Panel", "showGrievanceFloatPanel")
      .addSeparator()
      .addItem("📨 View Message Trail", "showMessageTrail")
      .addItem("🔄 Refresh Admin Highlights", "refreshAdminMessageHighlights"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📁 Google Drive")
      .addItem("📁 Setup Folder for Grievance", "setupDriveFolderForGrievance")
      .addItem("📎 Upload Files", "showFileUploadDialog")
      .addItem("📂 Show Grievance Files", "showGrievanceFiles"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📧 Communications")
      .addItem("📧 Compose Email", "composeGrievanceEmail")
      .addItem("📝 Email Templates", "showEmailTemplateManager")
      .addSeparator()
      .addItem("🔔 Notification Center", "showNotificationCenter")
      .addSeparator()
      .addItem("📧 Email Opt-Out Management", "showOptOutManagementPanel")
      .addItem("📊 Opt-Out Statistics", "showOptOutStatistics")
      .addSeparator()
      .addItem("📞 View Communications Log", "showGrievanceCommunications"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📊 Reports & Export")
      .addItem("📊 Custom Report Builder", "showCustomReportBuilder")
      .addSeparator()
      .addItem("📤 Export Wizard", "showExportWizard")
      .addItem("📥 Import Wizard", "showImportWizard")
      .addSeparator()
      .addItem("📄 Export Grievances to CSV", "exportGrievancesToCSV")
      .addItem("📄 Export Members to CSV", "exportMembersToCSV")
      .addItem("📊 Advanced Export Options", "showAdvancedExport"))
    .addSeparator()
    .addSubMenu(ui.createMenu("♿ Accessibility")
      .addItem("♿ ADHD Control Panel", "showADHDControlPanel")
      .addItem("🎨 Theme Manager", "showThemeManager")
      .addSeparator()
      .addItem("🌙 Quick Toggle Dark Mode", "quickToggleDarkMode")
      .addItem("🎯 Activate Focus Mode", "activateFocusMode")
      .addItem("🎯 Deactivate Focus Mode", "deactivateFocusMode")
      .addSeparator()
      .addItem("🦓 Toggle Zebra Stripes", "toggleZebraStripes")
      .addItem("🔲 Toggle Gridlines (ADHD)", "toggleGridlinesADHD")
      .addItem("🐢 Toggle Reduced Motion", "toggleReducedMotion"))
    .addSeparator()
    .addSubMenu(ui.createMenu("❓ Help & Support")
      .addItem("👋 Welcome Wizard", "showWelcomeWizard")
      .addItem("🚀 Getting Started Guide", "showGettingStartedGuide")
      .addItem("📚 Interactive Tutorial", "showInteractiveTutorial")
      .addItem("🎥 Video Tutorials", "showVideoTutorials")
      .addSeparator()
      .addItem("❓ Context Help (F1)", "showContextHelp")
      .addItem("📖 Enhanced Help", "showEnhancedHelp")
      .addItem("📋 Column Help", "showColumnHelp")
      .addItem("💡 Quick Tips", "showQuickTips")
      .addSeparator()
      .addItem("🔍 Search Help", "showHelpSearch")
      .addItem("⌨️ Keyboard Shortcuts", "showKeyboardShortcuts")
      .addSeparator()
      .addItem("📋 Release Notes", "showReleaseNotes")
      .addItem("🆕 What's New", "showWhatsNew")
      .addItem("📜 Version History", "showVersionHistory"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Quick Actions")
      .addItem("⚡ Quick Actions Menu", "showQuickActionsMenu")
      .addItem("📌 Quick Actions Sidebar", "showQuickActionsSidebar")
      .addSeparator()
      .addItem("👤 Member Quick Actions", "showMemberQuickActions")
      .addItem("📋 Grievance Quick Actions", "showGrievanceQuickActions")
      .addSeparator()
      .addItem("📝 Quick Capture Notepad", "showQuickCaptureNotepad"))
    .addToUi();

  // ------------ SHEET MANAGER MENU ------------
  ui.createMenu("📊 Sheet Manager")
    .addSubMenu(ui.createMenu("💾 Data Management")
      .addItem("💾 Backup & Recovery Manager", "showBackupManager")
      .addSeparator()
      .addItem("💾 Create Backup Now", "createBackup")
      .addItem("✅ Enable Automated Backups", "setupAutomatedBackups")
      .addItem("🔕 Disable Automated Backups", "disableAutomatedBackups")
      .addSeparator()
      .addItem("📊 View Backup Log", "navigateToBackupLog"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Performance")
      .addItem("🗄️ Cache Status Dashboard", "showCacheStatusDashboard")
      .addItem("📊 Performance Summary", "showPerformanceSummary")
      .addItem("📱 Device Analytics", "showDeviceAnalyticsDashboard")
      .addItem("👥 Session Dashboard", "showSessionDashboard")
      .addSeparator()
      .addItem("🔥 Warm Up All Caches", "warmUpCaches")
      .addItem("🗑️ Clear All Caches", "invalidateAllCaches"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔒 Data Integrity")
      .addItem("📊 Data Quality Dashboard", "showDataQualityDashboard")
      .addItem("🔍 Check Referential Integrity", "checkReferentialIntegrity")
      .addItem("📋 Validation Report", "showValidationReport")
      .addSeparator()
      .addItem("✅ Run Bulk Validation", "runBulkValidation")
      .addItem("⚙️ Validation Settings", "showValidationSettings")
      .addSeparator()
      .addItem("📝 Create Change Log Sheet", "createChangeLogSheet")
      .addItem("🆔 Generate Next Member ID", "showNextMemberID")
      .addItem("🆔 Generate Next Grievance ID", "showNextGrievanceID"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔐 PII Protection")
      .addItem("🔐 PII Protection Dashboard", "showPIIProtectionDashboard")
      .addItem("📤 Export with Masked PII", "exportMembersWithMaskedPII")
      .addItem("📊 PII Audit Report", "showPIIAuditReport")
      .addSeparator()
      .addItem("👤 Data Subject Request", "showDataSubjectRequestForm")
      .addItem("🔄 Anonymize Inactive Members", "anonymizeInactiveMembers"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🤖 Automations")
      .addItem("📬 Notification Settings", "showNotificationSettings")
      .addItem("📊 Report Automation Settings", "showReportAutomationSettings")
      .addItem("🔄 Auto-Refresh Settings", "showAutoRefreshSettings")
      .addSeparator()
      .addItem("✅ Enable Daily Deadline Notifications", "setupDailyDeadlineNotifications")
      .addItem("🔕 Disable Deadline Notifications", "disableDailyDeadlineNotifications")
      .addSeparator()
      .addItem("✅ Enable Monthly Reports", "setupMonthlyReports")
      .addItem("✅ Enable Quarterly Reports", "setupQuarterlyReports")
      .addItem("🔕 Disable All Reports", "disableAutomatedReports")
      .addSeparator()
      .addItem("⌨️ Setup Keyboard Shortcuts", "setupKeyboardShortcuts")
      .addItem("🔄 Setup Auto-Refresh Trigger", "setupAutoRefreshTrigger")
      .addItem("🔒 Setup Security Monitoring", "setupSuspiciousActivityMonitoring"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📁 Google Drive Integration")
      .addItem("📁 Batch Create All Folders", "batchCreateGrievanceFolders")
      .addItem("📁 Setup Drive Folders", "setupDriveFolderForGrievance"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📅 Calendar Integration")
      .addItem("📅 Sync Deadlines to Calendar", "syncDeadlinesToCalendar")
      .addItem("👀 View Upcoming Deadlines", "showUpcomingDeadlinesFromCalendar")
      .addSeparator()
      .addItem("🗑️ Clear All Calendar Events", "clearAllCalendarEvents"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📈 Analysis & Insights")
      .addItem("🔮 Predictive Analytics Dashboard", "showPredictiveAnalyticsDashboard")
      .addItem("📈 Generate Full Analysis", "performPredictiveAnalysis")
      .addItem("🔬 Root Cause Analysis", "showRootCauseAnalysisDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚡ Batch Operations")
      .addItem("⚡ Show Batch Operations Menu", "showBatchOperationsMenu")
      .addSeparator()
      .addItem("👤 Bulk Assign Steward", "batchAssignSteward")
      .addItem("📊 Bulk Update Status", "batchUpdateStatus")
      .addItem("📄 Bulk Export to PDF", "batchExportPDF")
      .addItem("📧 Bulk Email Notifications", "batchEmailNotifications")
      .addItem("📝 Bulk Add Notes", "batchAddNotes"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🤖 Smart Assignment")
      .addItem("🤖 Auto-Assign Steward", "showAutoAssignDialog")
      .addItem("📦 Batch Auto-Assign", "batchAutoAssign")
      .addSeparator()
      .addItem("👥 Steward Workload Dashboard", "showStewardWorkloadDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📚 Knowledge Base")
      .addItem("📚 Search FAQ", "showFAQSearch")
      .addItem("➕ Add New FAQ", "showFAQAdmin")
      .addSeparator()
      .addItem("📝 Create FAQ Database", "createFAQSheet"))
    .addToUi();

  // ------------ DEMO MENU ------------
  ui.createMenu("🎭 Demo")
    .addItem("⚙️ Populate Config Defaults (Run First!)", "populateConfigDefaults")
    .addSeparator()
    .addSubMenu(ui.createMenu("🌱 Seed Demo Data")
      .addSubMenu(ui.createMenu("👥 Seed Members")
        .addItem("Seed Members - Toggle 1 (5,000)", "SEED_MEMBERS_TOGGLE_1")
        .addItem("Seed Members - Toggle 2 (5,000)", "SEED_MEMBERS_TOGGLE_2")
        .addItem("Seed Members - Toggle 3 (5,000)", "SEED_MEMBERS_TOGGLE_3")
        .addItem("Seed Members - Toggle 4 (5,000)", "SEED_MEMBERS_TOGGLE_4")
        .addSeparator()
        .addItem("Seed All 20k Members (Legacy)", "SEED_20K_MEMBERS"))
      .addSubMenu(ui.createMenu("📋 Seed Grievances")
        .addItem("Seed Grievances - Toggle 1 (2,500)", "SEED_GRIEVANCES_TOGGLE_1")
        .addItem("Seed Grievances - Toggle 2 (2,500)", "SEED_GRIEVANCES_TOGGLE_2")
        .addSeparator()
        .addItem("Seed All 5k Grievances (Legacy)", "SEED_5K_GRIEVANCES"))
      .addSeparator()
      .addItem("📝 Add Sample Feedback Entries", "addSampleFeedbackEntries"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🗑️ Data Management")
      .addItem("🚨 Nuke All Data (Production Reset)", "nukeSeedData")
      .addItem("🗑️ Nuke ALL Sheet Data (Comprehensive)", "nukeAllSheetData")
      .addItem("⚠️ Clear Core Data Only", "clearAllData"))
    .addToUi();

  // ------------ ADMINISTRATOR MENU ------------
  ui.createMenu("⚙️ Administrator")
    .addSubMenu(ui.createMenu("⚠️ System Health")
      .addItem("⚠️ Error Dashboard", "showErrorDashboard")
      .addItem("🏥 Run Health Check", "performSystemHealthCheck")
      .addItem("📋 Schema Health Check", "showSchemaHealthCheck")
      .addSeparator()
      .addItem("📊 View Error Trends", "createErrorTrendReport")
      .addItem("🧪 Test Error Logging", "testErrorLogging"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔬 Root Cause Analysis")
      .addItem("🔬 Root Cause Analysis Dashboard", "showRootCauseAnalysisDashboard"))
    .addSeparator()
    .addSubMenu(ui.createMenu("🔄 Workflow Management")
      .addItem("🔄 Workflow Visualizer", "showWorkflowVisualizer")
      .addItem("🔄 Change Workflow State", "changeWorkflowState")
      .addItem("📊 View Current State", "showCurrentWorkflowState")
      .addSeparator()
      .addItem("📦 Batch Update State", "batchUpdateWorkflowState"))
    .addSeparator()
    .addSubMenu(ui.createMenu("👁️ Column Toggles & View")
      .addItem("Toggle Level 2 Member Columns", "toggleLevel2Columns")
      .addItem("Toggle Engagement Metrics", "toggleEngagementMetricsColumns")
      .addItem("Toggle Member Interests", "toggleMemberInterestsColumns")
      .addItem("Toggle Engagement & Interests", "toggleEngagementAndInterestsColumns")
      .addItem("Show All Member Columns", "showAllMemberColumns")
      .addSeparator()
      .addItem("📨 Toggle Admin Message Columns", "toggleAdminMessageColumns")
      .addItem("Show All Grievance Columns", "showAllGrievanceColumns")
      .addItem("🔧 Setup Admin Message Columns", "setupAdminMessageColumns")
      .addItem("⚡ Install Admin Message Trigger", "installAdminMessageTrigger")
      .addSeparator()
      .addItem("🔄 Refresh Grievance Formulas", "refreshGrievanceFormulas")
      .addItem("🔄 Refresh Dashboard Deadlines", "refreshDashboardDeadlines")
      .addItem("🧹 Cleanup Extra Member Columns", "cleanupMemberDirectoryColumns")
      .addSeparator()
      .addItem("👁️ Hide Diagnostics Tab", "hideDiagnosticsTab")
      .addItem("Reorder Sheets Logically", "reorderSheetsLogically")
      .addItem("Hide Gridlines (Focus Mode)", "hideAllGridlines")
      .addItem("Show Gridlines", "showAllGridlines")
      .addItem("🎯 Toggle Complexity Indicators", "toggleComplexityIndicators")
      .addItem("Setup ADHD Defaults", "setupADHDDefaults"))
    .addSeparator()
    .addSubMenu(ui.createMenu("↩️ History & Undo")
      .addItem("↩️ Undo/Redo History", "showUndoRedoPanel")
      .addItem("⌨️ Install Undo Shortcuts", "installUndoRedoShortcuts")
      .addSeparator()
      .addItem("↩️ Undo Last Action (Ctrl+Z)", "undoLastAction")
      .addItem("↪️ Redo Last Action (Ctrl+Y)", "redoLastAction")
      .addSeparator()
      .addItem("🗑️ Clear Undo History", "clearUndoHistory"))
    .addSeparator()
    .addSubMenu(ui.createMenu("📱 Mobile & Viewing")
      .addItem("📱 Mobile Dashboard", "showMobileDashboard")
      .addItem("📋 Mobile Grievance List", "showMobileGrievanceList")
      .addItem("📋 Mobile Grievance Browser", "showMobileGrievanceBrowser")
      .addItem("👥 Mobile Member Browser", "showMobileMemberBrowser")
      .addItem("🔍 Mobile Unified Search", "showMobileUnifiedSearch")
      .addSeparator()
      .addItem("📄 Paginated Data Viewer", "showPaginatedViewer"))
    .addSeparator()
    .addSubMenu(ui.createMenu("👥 User Roles (RBAC)")
      .addItem("Initialize RBAC", "initializeRBAC")
      .addItem("Configure Roles", "configureUserRoles")
      .addSeparator()
      .addItem("Add Admin", "addAdmin")
      .addItem("Add Steward", "addSteward")
      .addItem("Add Viewer", "addViewer")
      .addSeparator()
      .addItem("My Permissions", "showMyPermissions"))
    .addSeparator()
    .addSubMenu(ui.createMenu("⚙️ User Settings")
      .addItem("⚙️ Preferences Editor", "showPreferencesEditor")
      .addItem("🌐 Language Selector", "showLanguageSelector"))
    .addToUi();
}

/**
 * Legacy wrapper for backwards compatibility
 * Calls createReorganizedMenus() directly
 */
function onOpen_Reorganized() {
  createReorganizedMenus();
}
